### PR TITLE
Add missing run_exports and add @traversaro to mantainers

### PR DESCRIPTION
**Pull request by traversaro**
In https://github.com/conda-forge/idyntree-feedstock/pull/59 I am compiling a package that links glfw and then the test fail with error:
~~~
2023-05-09T12:52:16.3748464Z import: 'idyntree'
2023-05-09T12:52:16.4045454Z Traceback (most recent call last):
2023-05-09T12:52:16.4045923Z   File "/home/conda/feedstock_root/build_artifacts/idyntree_1683636242691/test_tmp/run_test.py", line 2, in <module>
2023-05-09T12:52:16.4046160Z     import idyntree
2023-05-09T12:52:16.4047126Z   File "/home/conda/feedstock_root/build_artifacts/idyntree_1683636242691/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/pypy3.8/site-packages/idyntree/__init__.py", line 1, in <module>
2023-05-09T12:52:16.4047570Z     from . import swig
2023-05-09T12:52:16.4048155Z   File "/home/conda/feedstock_root/build_artifacts/idyntree_1683636242691/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/pypy3.8/site-packages/idyntree/swig.py", line 10, in <module>
2023-05-09T12:52:16.4048510Z     from . import _iDynTree
2023-05-09T12:52:16.4048704Z ImportError: libglfw.so.3: cannot open shared object file: No such file or directory
~~~

It seems that this is due to glfw missing a proper `run_exports`. glfw is quite ABI back-compatible (see https://abi-laboratory.pro/index.php?view=timeline&l=glfw), so I guess that just a run_exports on the major version is ok.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by kmuehlbauer** [comment]
@traversaro I'm not well versed when it comes to these parts of conda-forge. I was also slowly transitioning away from using OpenGL. Would you consider stepping in as maintainer, here?

**Comment by traversaro** [comment]
> @traversaro I'm not well versed when it comes to these parts of conda-forge. I was also slowly transitioning away from using OpenGL. Would you consider stepping in as maintainer, here?

Sure!

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by kmuehlbauer** [comment]
Great! Let's have @hmaarrfk and @hoechenberger a final look here.

**Review by hoechenberger — APPROVED** [review]

**Pull request merged**
